#!/bin/bash -login
#PBS -l nodes=1:ppn=24,walltime=3:00:00:00,mem=384gb

module load ABySS/1.3.5

cd $PBS_O_WORKDIR

K=31

WORK=ABySS-raw-K${K}
mkdir -p ${WORK}
cd ${WORK}

ln -s ../*.trim.fq.keep .

abyss-pe v=-v k=${K} name=raw-lamprey-germline np=${PBS_NUM_PPN} lib="ACAGTG_L001 ACAGTG_L002 GCCAAT_L001 GCCAAT_L002 CCTGTA_L001 CCTGTA_L002 GTGAAA_L001 GTGAAA_L002" ACAGTG_L001="2_ACAGTG_L001_R1_001.trim.fq.keep 2_ACAGTG_L001_R2_001.trim.fq.keep" ACAGTG_L002="2_ACAGTG_L002_R1_001.trim.fq.keep 2_ACAGTG_L002_R2_001.trim.fq.keep" GCCAAT_L001="4_GCCAAT_L001_R1_001.trim.fq.keep 4_GCCAAT_L001_R2_001.trim.fq.keep" GCCAAT_L002="4_GCCAAT_L002_R1_001.trim.fq.keep 4_GCCAAT_L002_R2_001.trim.fq.keep" CCTGTA_L001="5_CTTGTA_L001_R1_001.trim.fq.keep 5_CTTGTA_L001_R2_001.trim.fq.keep" CCTGTA_L002="5_CTTGTA_L002_R1_001.trim.fq.keep 5_CTTGTA_L002_R2_001.trim.fq.keep" GTGAAA_L001="6_GTGAAA_L001_R1_001.trim.fq.keep 6_GTGAAA_L001_R2_001.trim.fq.keep" GTGAAA_L002="6_GTGAAA_L002_R1_001.trim.fq.keep 6_GTGAAA_L002_R2_001.trim.fq.keep"
