#!/usr/bin/env python

from peasoup import configtools
from peasoup import task_funcs
from peasoup.task_funcs import run_tasks, apply_run_task
import pandas as pd
import os
import argparse

BOWTIE_THREADS = 1

@task_funcs.create_task_object
def bowtie2_build_task(row):
    return task_funcs.bowtie2_build_task(row.fn, row.fn.split('.fasta')[0])

@task_funcs.create_task_object
def split_pairs_task(row):
    return task_funcs.split_pairs_task(row.filename)

@task_funcs.create_task_object
def bowtie2_align_task(row, idx_fn):
    target = '{sample}.x.{idx}'.format(sample=row.filename, idx=idx_fn)
    if row.paired == False:
        return task_funcs.bowtie2_align_task(idx_fn, target, singleton_fn=row.filename, num_threads=BOWTIE_THREADS)
    else:
        return task_funcs.bowtie2_align_task(idx_fn, target, left_fn=row.filename+'.1',
                                                right_fn=row.filename + '.2', num_threads=BOWTIE_THREADS)

@task_funcs.create_task_object
def express_task(hits_fn, transcripts_fn):
    folder = hits_fn.split('.bam')[0]
    return task_funcs.eXpress_task(transcripts_fn, hits_fn, folder)

@task_funcs.create_task_object
def samtools_sort_task(hits_fn):
    return task_funcs.samtools_sort_task(hits_fn)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--metadata', default='metadata.ini')
    parser.add_argument('--metadata-spec', dest='metadata_spec',  default='metadata.spec.ini')
    parser.add_argument('--wdir', default='work')
    parser.add_argument('--print-tasks', dest='print_tasks', action='store_true', default=False)
    args, doit_args = parser.parse_known_args()

    metadata = configtools.get_cfg(args.metadata, args.metadata_spec)
    db_df = configtools.cfg_to_dataframe(metadata['urls'])
    db_df['fn'] = db_df.dest.apply(lambda s: s.rstrip('.gz'))
    sample_df = configtools.cfg_to_dataframe(metadata['samples'])

    old_dir = os.getcwd()
    try:
        if not os.path.exists(args.wdir):
            os.makedirs(args.wdir)
        os.chdir(args.wdir)

        tasks = []
    
        build_task = bowtie2_build_task(db_df.ix['assembly'])
        index_basename_fn = build_task.targets[-1]
        tasks.extend([build_task])

        split_tasks = sample_df[sample_df.paired == True].apply(split_pairs_task, axis=1, reduce=False)
        tasks.extend(list(split_tasks))

        align_tasks = sample_df.apply(bowtie2_align_task, args=(index_basename_fn,), axis=1, reduce=False)
        tasks.extend(list(align_tasks))

        align_files_df = task_funcs.get_task_files_df(align_tasks)
        bam_files_to_sort = align_files_df[align_files_df.apply(lambda row: row.dep.endswith('.1'), axis=1)].target
        bam_files_single = align_files_df[align_files_df.apply(lambda row: row.dep.endswith('.fq.gz'), axis=1)].target
        
        sort_tasks = bam_files_to_sort.apply(samtools_sort_task)
        tasks.extend(sort_tasks)

        hits_files = bam_files_single.append(sort_tasks.apply(lambda t: t.targets[0]))
        express_tasks = hits_files.apply(express_task, args=(db_df.ix['assembly'].fn,))
        tasks.extend(express_tasks)

        if args.print_tasks:
            for task in tasks:
                print '-----\n', task, task.actions

        run_tasks(tasks, doit_args)
    
    finally:
        os.chdir(old_dir)

main()
