KHMER=/w/khmer
PEASOUP=/w/peasoup/scripts
SEQCLEAN=seqclean
CDHITEST=cd-hit-est

CSV=qseqid sseqid length nident qstart qend sstart send bitscore evalue
BLAST_EVALUE=0.001
BLAST_CPUS=8
BLASTRES=nodes=1:ppn=9,walltime=48:00:00,mem=8gb

define newline

endef
